# Generated by Django 4.2.27 on 2026-01-07 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("bark", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(max_length=255)),
                ("plate_number", models.CharField(blank=True, default="", max_length=50)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="vehicles", to="core.customer")),
            ],
        ),
        migrations.AddField(
            model_name="repairjob",
            name="customer_new",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="bark_jobs", to="core.customer"),
        ),
        migrations.AddField(
            model_name="repairjob",
            name="insurance_new",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="repair_jobs", to="bark.insurancecompany"),
        ),
        migrations.AddField(
            model_name="repairjob",
            name="vehicle_new",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="repair_jobs", to="bark.vehicle"),
        ),
    ]
