# Generated by Django 4.2.27 on 2026-01-07 01:33

from django.db import migrations


def forwards(apps, schema_editor):
    CustomerData = apps.get_model("bark", "Customer_Data")
    RepairJob = apps.get_model("bark", "RepairJob")
    Customer = apps.get_model("core", "Customer")
    Vehicle = apps.get_model("bark", "Vehicle")
    InsuranceCompany = apps.get_model("bark", "InsuranceCompany")

    customer_map = {}

    for legacy in CustomerData.objects.all():
        customer = Customer.objects.create(full_name="UNKNOWN")
        insurance_name = (legacy.insurance or "").strip() or "UNKNOWN"
        car_model = (legacy.car_model or "").strip() or "UNKNOWN"

        insurance, _ = InsuranceCompany.objects.get_or_create(name=insurance_name)
        vehicle, _ = Vehicle.objects.get_or_create(owner=customer, model=car_model)

        customer_map[legacy.pk] = (customer, vehicle, insurance)

    for job in RepairJob.objects.select_related("customer").all():
        if job.customer_id in customer_map:
            customer, vehicle, insurance = customer_map[job.customer_id]
            job.customer_new = customer
            job.vehicle_new = vehicle
            job.insurance_new = insurance
            job.save(update_fields=["customer_new", "vehicle_new", "insurance_new"])


def backwards(apps, schema_editor):
    RepairJob = apps.get_model("bark", "RepairJob")
    for job in RepairJob.objects.all():
        job.customer_new = None
        job.vehicle_new = None
        job.insurance_new = None
        job.save(update_fields=["customer_new", "vehicle_new", "insurance_new"])


class Migration(migrations.Migration):

    dependencies = [
        ("bark", "0002_add_new_entities"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
