# Generated by Django 4.2.27 on 2026-01-07 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bark", "0003_migrate_customer_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repairjob",
            name="customer",
        ),
        migrations.RenameField(
            model_name="repairjob",
            old_name="customer_new",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="repairjob",
            old_name="vehicle_new",
            new_name="vehicle",
        ),
        migrations.RenameField(
            model_name="repairjob",
            old_name="insurance_new",
            new_name="insurance",
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bark_jobs", to="core.customer"),
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="vehicle",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="repair_jobs", to="bark.vehicle"),
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="insurance",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="repair_jobs", to="bark.insurancecompany"),
        ),
        migrations.DeleteModel(
            name="Customer_Data",
        ),
    ]
