# Generated by Django 4.2.27 on 2026-01-07 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bark', '0004_cleanup_customer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='repair_damages/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='status_name',
        ),
        migrations.RemoveField(
            model_name='repairjob',
            name='images',
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairjob',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default='exit', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repairjob',
            name='approved_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='repairjob',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bark.status'),
        ),
        migrations.DeleteModel(
            name='Status_Log',
        ),
        migrations.AddField(
            model_name='statuslog',
            name='repair_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bark.repairjob'),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bark.status'),
        ),
        migrations.AddField(
            model_name='jobmedia',
            name='repair_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='bark.repairjob'),
        ),
    ]
