# Generated by Django 4.2.27 on 2026-01-06 09:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('car_model', models.CharField(max_length=255)),
                ('insurance', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repairjob_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='repair_damages/')),
                ('estimate_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate_date', models.DateTimeField(auto_now_add=True)),
                ('repair_order', models.TextField()),
                ('job_order', models.TextField()),
                ('approved_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_repair_order', models.TextField(blank=True, null=True)),
                ('approved_job_order', models.TextField(blank=True, null=True)),
                ('loa_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('APPROVAL', 'LOA & INSURANCE'), ('PARTS', 'Parts Procurement'), ('REPAIR', 'Repair Shop Stage'), ('PICKUP', 'Releasing Stage'), ('BILLING', 'Insurance Claims'), ('DISMANTLE', 'Total Wreck')], max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('repair_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.repairjob')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
        ),
        migrations.AddField(
            model_name='repairjob',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_jobs', to='core.status'),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.customer_data'),
        ),
    ]
